### PR TITLE
fix(lifecycles): BeforeDeleteMany lifecycle will correctly fetch results

### LINKED ISSUE #26: Error when trying to delete locale
### Describe the bug

When trying to delete a locale I am just met with a generic strapi error in the interface. In the console I am getting a more detailed error:

```
[2023-02-08 14:29:42.995] error: Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at Object.beforeDeleteMany (/home/.../node_modules/@strapi-community/strapi-plugin-url-alias/server/admin-api/services/lifecycle.js:125:47)
```

### Steps to reproduce the behavior

1. Create a new locale by going to Settings -> Internationalization -> + Create new locale
2. click on the delete button next to it and confirm
3. You will be met with a similar error

### Expected behavior

The locale would be deleted

### System

- Node.js version: 
- NPM version: 9
- Strapi version: 4.6.0
- Plugin version: 1.0.0-alpha.6
- Database: sqlite
- Operating system: NixOS (Linux)

### PR DESCRIPTION
**Pull request by Alexnortung**
### What does it do?

Since we do not know what the params of the event is, we can use those events in a query and fetch the correct entries. We can then delete the correct url paths

### Why is it needed?

fixes #26

### How to test it?

Deleting a locale should now work

### Related issue(s)/PR(s)

#26

### CODE REVIEW

File: server/index.ts [hunk 1]
```diff
@@ -1,7 +1,7 @@
 "use strict";
 
 // Has to be imported once for build
-import { } from '@strapi/strapi';
+import _, { } from '@strapi/strapi';
```
Comment (boazpoolman) [inline server/index.ts:4]: I don't get why you import _ of off `@strapi/strapi`.
Could you elaborate?

File: server/admin-api/services/lifecycle.ts [hunk 2]
```diff
@@ -123,10 +158,20 @@ const subscribeLifecycleMethods = async (modelName) => {
...
       async beforeDeleteMany(event) {
-        const ids = event.params.where.$and[0].id.$in;
-        for (let i = 0; i < ids.length; i++) {
-          // eslint-disable-next-line no-await-in-loop
-          await deleteEntity(event, ids[i]);
+        const result = await strapi.db.query(modelName).findMany({
+          ...event.params,
+        });
+
+        console.log(result);
```
Comment (boazpoolman) [inline server/admin-api/services/lifecycle.ts:165]: Could you remove the console.log here?

File: server/admin-api/services/lifecycle.ts [hunk 3]
```diff
@@ -123,10 +158,20 @@ const subscribeLifecycleMethods = async (modelName) => {
 
       // Delete the path entity.
       async beforeDeleteMany(event) {
-        const ids = event.params.where.$and[0].id.$in;
-        for (let i = 0; i < ids.length; i++) {
-          // eslint-disable-next-line no-await-in-loop
-          await deleteEntity(event, ids[i]);
+        const result = await strapi.db.query(modelName).findMany({
```
Comment (boazpoolman) [inline server/admin-api/services/lifecycle.ts:161]: Is there a specific reason you didn't use the entityService layer here?

**Review by boazpoolman — CHANGES_REQUESTED** [review]

File: server/index.ts (hunk 1 above)
Comment (Alexnortung) [reply server/index.ts:4]: I just called it _ because it is not being used. However I had to import the default too, to avoid typescript saying strapi is not defined in all of the files.

If you try removing the _ and opening a file such as `lifecycles.ts` you should see an error every time strapi is used saying 'strapi' is not defined. Eslint would also throw some warnings for this.

File: server/admin-api/services/lifecycle.ts (hunk 3 above)
Comment (Alexnortung) [reply server/admin-api/services/lifecycle.ts:161]: The params of the event directly map to using the strapi query. The entity service does not use `where` anywhere, so they would be incompatible. Doing it this way we can be certain that it would fetch the same entries as are being deleted :)

File: server/index.ts (hunk 1 above)
Comment (Alexnortung) [reply server/index.ts:4]: I'm sorry, I just tried this again myself and it does not seem like an issue, I will remove it again

**Review by boazpoolman — APPROVED** [review]
LGTM
